"""
Django settings for Progressao project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
from django.contrib.messages import constants as messages
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['200.225.120.236', '192.168.137.9','localhost', '127.0.0.0']
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authUser.apps.AuthuserConfig',
    #'nomedoapp.apps.NomedoAppConfig',
    'paginas.apps.PaginasConfig',
    'cadastros.apps.CadastrosConfig',
    'Filipetas.apps.FilipetasConfig',
    'equipamentos.apps.EquipamentosConfig',
    'estabelecimentos.apps.EstabelecimentosConfig',
    'profissionais.apps.ProfissionaisConfig',
    'gestantes.apps.GestantesConfig',
    'agendas.apps.AgendasConfig',
    'unidadeDemanda.apps.UnidadedemandaConfig',
    'malotes.apps.MalotesConfig',
    'relatorios.apps.RelatoriosConfig',
    'analytics.apps.AnalyticsConfig',
    'support.apps.SupportConfig',
    'import.apps.ImportConfig',
    'esus.apps.EsusConfig',
    'django_cleanup.apps.CleanupConfig',
    'contato.apps.ContatoConfig',
    'classificacaoDeRisco.apps.ClassificacaoderiscoConfig',
    'crispy_forms',
    'fontawesomefree',
    'django.contrib.humanize',
]
# Crispy Forms 
CRISPY_TEMPLATE_PACK = 'bootstrap4'
USE_THOUSAND_SEPARATOR = False


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Progressao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
 }

WSGI_APPLICATION = 'Progressao.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pmbp_saude_permuta_dev',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '',
        'PORT': '3306',
    },
    # 'esus': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': '',
    #     'USER': '',
    #     'PASSWORD': '#220683',
    #     'HOST': '',
    #     'PORT': '5432',
    # }
}

HCAPTCHA_DEFAULT_CONFIG = {
    'onload': 'name_of_js_function',
    'render': 'explicit',
    'theme': 'dark',  # do not use data- prefix
    'size': 'compact',  # do not use data- prefix
}

HCAPTCHA_PROXIES = {
   'http': 'http://127.0.0.1:8000',
}

HCAPTCHA_TIMEOUT = 5

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')    
]

MEDIA_ROOT = os.path.join(BASE_DIR, "uploads")
MEDIA_URL = "/uploads/"

STATIC_ROOT = "root-static"

LOGIN_REDIRECT_URL = 'index'

LOGOUT_REDIRECT_URL = 'userLogin'

LOGIN_URL = 'userLogin'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# SESSION_COOKIE_AGE = 14400

HCAPTCHA_SITEKEY = 'c66f9429-98a8-4956-ab7c-cd96172484f7'
HCAPTCHA_SECRET = 'ES_0d6fadaed4214f46853faf2a36414522'

