# Generated by Django 3.2.7 on 2023-06-27 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cns', models.CharField(blank=True, max_length=19, null=True, unique=True, verbose_name='Cartao Sus')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('sexo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Sexo')),
                ('dataNascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('altura', models.CharField(default='0', max_length=4, verbose_name='Altura')),
                ('peso', models.CharField(default='0', max_length=6, verbose_name='Peso')),
                ('nomeDaMae', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe')),
                ('nomeDoPai', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Pai')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentário')),
                ('telefone1', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone/Celular')),
                ('telefone2', models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone para Recado')),
                ('celular1', models.CharField(blank=True, max_length=16, null=True, verbose_name='Celular para Contato')),
                ('celular2', models.CharField(blank=True, max_length=16, null=True, verbose_name='Celular para Recado')),
                ('allowMessage', models.BooleanField(default=False, verbose_name='Aceita receber mensagem? (Ex: Whatsapp, Telegram, sms...)')),
                ('isVisible', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=15, null=True)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('cargo', models.CharField(max_length=50, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Telefone'), (2, 'Celular'), (3, 'E-mail'), (4, 'Facebook'), (5, 'IG'), (6, 'Linkedin'), (7, 'Whatsapp')], default=1)),
                ('contato', models.CharField(max_length=100, verbose_name='Contato')),
                ('allowMessage', models.BooleanField(default=False, verbose_name='Aceita receber mensagem nesse contato?')),
                ('isVisible', models.BooleanField(default=True)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
